version: "3.8"
services:
  dev:
    image: ryusa/bootcamp-react:2020
    ports:
      - 3000:3000
    tty: true
    container_name: bootcamp-react

  mock-server:
    image: ryusa/bootcamp-react-mock:2020
    ports:
      - 5000:5000
    container_name: bootcamp-react-mock
